name: projection

cnn_config:
  name: vgg
  vgg_version: "11"
  batch_norm: false
  num_layers_freeze: 8
  num_classes: 32
  pretrained: false

gcn_config:
  name: monet
  kernel_size: 25
  num_node_features: 3
  monet_params:
    hidden_layer_sizes: [32,64,64]
  linear_layer_params:
    intermediate_layer_sizes: []
  num_classes: 32

num_classes: 10