cnn_config:
  batch_norm: false
  name: vgg
  num_classes: 4
  num_layers_freeze: 0
  pretrained: false
  vgg_version: '11'
gnn_config:
  gat_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  linear_layer_params:
    intermediate_layer_sizes: []
  name: gat
  num_classes: 4
  num_node_features: 3
name: hybrid
