cnn_config:
  cnn_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  linear_layer_params:
    intermediate_layer_sizes: []
  name: cnn
  num_classes: 62
  num_input_channels: 3
gnn_config:
  mlp_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  name: mlp
  num_classes: 62
  num_input_features: 8742
name: hybrid
