dataloader_type: geometric
grid_search:
  directory: null
  hyperparams:
    train:
      loader_params:
        batch_size:
          - 256
          - 128
      log:
        log_label: null
        vals:
          hparams:
            - name: epochs
              path:
                - train
                - max_epochs
            - name: batch_size
              path:
                - train
                - loader_params
                - batch_size
            - name: optimizer_params
              path:
                - train
                - optimizer
                - params
            - name: optimizer_type
              path:
                - train
                - optimizer
                - type
      max_epochs:
        - 100
      optimizer:
        params:
          lr:
            - 0.001
            - 0.0001
            - 1.0e-05
          weight_decay:
            - 0
            - 0.001
        type:
          - adam_w
input_key:
  - graph
  - image
main_config:
  device: &id001
    name: cuda
  metrics: &id002
    - params:
        normalize: true
      type: sklearn_acc
  seed: 42
train:
  append_text: train
  checkpoint:
    checkpoint_dir: ckpts/
  criterion:
    params: null
    type: CrossEntropyLoss
  device: *id001
  interval_type: epoch
  label_type: logit
  loader_params:
    batch_size: 128
    num_workers: 2
    shuffle: true
  log:
    log_interval: 1
    log_label: 1
    vals:
      hparams: null
      loss: true
      metrics: true
  log_and_val_interval: 1
  max_epochs: 86
  metrics: *id002
  optimizer:
    params:
      betas:
        - 0.9
        - 0.998
      weight_decay: 0.001
      eps: 1.0e-08
      lr: 0.001
    type: adam_w
  save_after_epoch: false
  save_on:
    best_path: ckpts/best_{}.pth
    desired: max
    final_path: ckpts/final_{}.pth
    score: sklearn_acc
  scheduler: null
  seed: 42
  val_interval: 1
trainer_name: base_trainer
val:
  append_text: val
  device: *id001
  loader_params:
    batch_size: 128
    num_workers: 2
    shuffle: false
  max_steps: null
  metrics: *id002
  seed: 42
version: 1.0
