main: &main
  name: mnist_slic
  
  transform_args:
    - type: ToPILImage
      params: null
    - type: Grayscale
      params:
        num_output_channels: 1
    - type: ToTensor
      params: null # Need to write it at as null if no parameters are passed,
    - type: Normalize
      params:
        mean: [0.2860402]
        std: [0.3530239]
    - type: ToSLIC
      params:
        n_segments: 75
        add_seg: true
        add_img: true
    - type: RadiusGraph
      params:
        r: 10
train_val:
  train: &train_2
    <<: *main
    split: train
    filepath:
      image: ./raw_data/FashionMNIST/train-images-idx3-ubyte
      labels: ./raw_data/FashionMNIST/train-labels-idx1-ubyte
      indices_csv: ./raw_data/FashionMNIST/FashionMNIST_training.csv
  val: &val_2
    <<: *main
    split: val
    filepath: 
      image: ./raw_data/FashionMNIST/train-images-idx3-ubyte
      labels: ./raw_data/FashionMNIST/train-labels-idx1-ubyte
      indices_csv: ./raw_data/FashionMNIST/FashionMNIST_validation.csv
train: &train
  <<: *main
  split: train
  filepath:
    image: ./raw_data/FashionMNIST/train-images-idx3-ubyte
    labels: ./raw_data/FashionMNIST/train-labels-idx1-ubyte
    indices_csv: null

val: &val
  <<: *main
  split: val
  filepath: 
    image: ./raw_data/FashionMNIST/t10k-images-idx3-ubyte
    labels: ./raw_data/FashionMNIST/t10k-labels-idx1-ubyte
    indices_csv: null
