cnn_config:
  mlp_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  name: mlp
  num_classes: 10
  num_input_features: 3072
gnn_config:
  kernel_size: 25
  linear_layer_params:
    intermediate_layer_sizes: []
  monet_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  name: monet
  num_classes: 10
  num_node_features: 5
name: hybrid
