cnn_config:
  cnn_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  linear_layer_params:
    intermediate_layer_sizes: []
  name: cnn
  num_classes: 32
  num_input_channels: 1
gnn_config:
  mlp_params:
    hidden_layer_sizes:
    - 32
  name: mlp
  num_classes: 32
  num_input_features: 784
name: projection
num_classes: 10
