main:
  name: mnist_slic
  transform_args: &id001
  - params: null
    type: ToPILImage
  - params:
      num_output_channels: 1
    type: Grayscale
  - params: null
    type: ToTensor
  - params:
      mean:
      - 0.2860402
      std:
      - 0.3530239
    type: Normalize
  - params:
      add_img: true
      add_seg: true
      n_segments: 75
    type: ToSLIC
  - params:
      r: 5
    type: RadiusGraph
  - params: null
    type: PolarTransformation
train:
  filepath:
    image: ./raw_data/FashionMNIST/train-images-idx3-ubyte
    indices_csv: null
    labels: ./raw_data/FashionMNIST/train-labels-idx1-ubyte
  name: mnist_slic
  split: train
  transform_args: *id001
train_val:
  train:
    filepath:
      image: ./raw_data/FashionMNIST/train-images-idx3-ubyte
      indices_csv: ./raw_data/FashionMNIST/FashionMNIST_training.csv
      labels: ./raw_data/FashionMNIST/train-labels-idx1-ubyte
    name: mnist_slic
    split: train
    transform_args: *id001
  val:
    filepath:
      image: ./raw_data/FashionMNIST/train-images-idx3-ubyte
      indices_csv: ./raw_data/FashionMNIST/FashionMNIST_validation.csv
      labels: ./raw_data/FashionMNIST/train-labels-idx1-ubyte
    name: mnist_slic
    split: val
    transform_args: *id001
val:
  filepath:
    image: ./raw_data/FashionMNIST/t10k-images-idx3-ubyte
    indices_csv: null
    labels: ./raw_data/FashionMNIST/t10k-labels-idx1-ubyte
  name: mnist_slic
  split: val
  transform_args: *id001
