cnn_config:
  mlp_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  name: mlp
  num_classes: 32
  num_input_features: 65536
gnn_config:
  kernel_size: 25
  linear_layer_params:
    intermediate_layer_sizes: []
  monet_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  name: monet
  num_classes: 32
  num_node_features: 3
name: projection
num_classes: 4
