name: cnn_gcn_projection

cnn_config:
  name: simple_cnn
  num_input_channels: 1
  cnn_params:
    hidden_layer_sizes: [32,64,64]
  linear_layer_params:
    intermediate_layer_sizes: []
  num_classes: 32
  # input_dim: 28

gcn_config:
  name: monet
  kernel_size: 25
  num_input_channels: 1
  monet_params:
    hidden_layer_sizes: [32,64,64]
  linear_layer_params:
    intermediate_layer_sizes: []
  num_classes: 32

num_classes: 10