results_dir: "./results"
metric: hf_accuracy
args:
  output_dir: ${results_dir}/ckpts/
  evaluation_strategy: steps
  eval_steps: 500
  logging_steps: 500
  logging_first_step: true
  logging_dir: ${results_dir}/logs/
  learning_rate: 1e-5
  save_steps: 500
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  num_train_epochs: 10
  dataloader_num_workers: 4
  weight_decay: 0.01
  seed: 42
  label_names: 
    - 'labels'
save_model_path: ${results_dir}/final_model/