trainer_name: hybrid_trainer
version: 1.0
dataloader_type: geometric
input_key:
  - graph
  - image

main_config: &main
  seed: 42
  metrics:
    - type: sklearn_acc
      params:
        normalize: true
  device:
    name: cuda

train: &train
  <<: *main
  # Can add the max_epochs vs max_steps functionality
  label_type: logit
  append_text: train
  max_epochs: 82
  loader_params:
    batch_size: 256
    num_workers: 2
    shuffle: true
  save_after_epoch: false
  optimizer:
    type: adam_w
    params:
      weight_decay: !!float 1e-3
      lr: !!float 1e-3
      betas: [0.9, 0.998]
      eps: !!float 1e-8

  scheduler: null

  criterion:
    type: HybridLoss
    params:
      alpha: 0.75

  save_on: ##Best Model/Final Model Saving
    score: sklearn_acc
    desired: max
    best_path: "ckpts/best_{}.pth" ## Number should be same as log_label
    final_path: "ckpts/final_{}.pth" ## Number should be same as log_label

  checkpoint:
    checkpoint_dir: "ckpts/" #For checkpoint saving after every epoch.

  interval_type: epoch
  log_and_val_interval: 1 ## Set to null if using different val and log intervals, Overrides log_interval nd val_interval

  val_interval: 1 # Global steps
  log:
    log_interval: 1 # Global Steps
    log_label: 1
    vals:
      loss: true
      metrics: true
      hparams: null

val:
  <<: *main
  append_text: val
  max_steps: null
  loader_params:
    batch_size: 256
    num_workers: 2
    shuffle: false

grid_search:
  directory: null
  hyperparams:
    train:
      criterion:
        type: HybridLoss
        params:
          alpha: 0.75
      max_epochs:
        - !!int 100
      loader_params:
        batch_size:
          - !!int 256
          - !!int 128
      optimizer:
        type:
          - adam_w
          # - adam
        params:
          lr:
            - !!float 1e-3
            - !!float 1e-4
            - !!float 1e-5
          weight_decay:
            - 0
            - 0.001

      log:
        log_label: null
        vals:
          hparams: ## Can have lists inside hparams
            - name: epochs
              path:
                - train
                - max_epochs
            - name: batch_size
              path:
                - train
                - loader_params
                - batch_size
            - name: optimizer_params
              path:
                - train
                - optimizer
                - params
            - name: optimizer_type
              path:
                - train
                - optimizer
                - type
