name: hf_image_classification
image_column_name: image
label_column_name: label
channels_first_input: true
remove_columns: null
load_dataset_args:
  path: fashion_mnist
transform_args:
  - type: ToPILImage
    params: null
  - type: Grayscale
    params:
      num_output_channels: 1
  - type: ToTensor
    params: null # Need to write it at as null if no parameters are passed,
  - type: Normalize
    params:
      mean: [0.2860402]
      std: [ 0.3530239]
features:
  image_output_shape: [1,28,28]
  label_names: ["0","1","2","3","4","5","6","7","8","9"]