
main: &main
  name: mnist_slic
  add_slic_mask: true
  transform_args:
    - type: ToPILImage
      params: null
    - type: Grayscale
      params:
        num_output_channels: 1
    - type: ToTensor
      params: null # Need to write it at as null if no parameters are passed,
    - type: Normalize
      params:
        mean: [0.13066062]
        std: [0.30810776]
    - type: RAGGraph
      params:
        n_segments: 75
        add_seg: true
        add_img: true
        # compactness: 0.001
        # max_size_factor: 2


    # - type: MnistSLIC
    #   params:
    #     n_segments: 74
    #     add_seg: true
    #     add_img: true
    # - type: KNNGraph
    #   params:
    #     k: 3
    #     force_undirected: true

train: &train
  <<: *main
  split: train
  filepath:
    image: ../raw_data/FashionMNIST/train-images-idx3-ubyte
    labels: ../raw_data/FashionMNIST/train-labels-idx1-ubyte
val: &val
  <<: *main
  split: val
  filepath: 
    image: ../raw_data/FashionMNIST/t10k-images-idx3-ubyte
    labels: ../raw_data/FashionMNIST/t10k-labels-idx1-ubyte
