cnn_config:
  cnn_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  linear_layer_params:
    intermediate_layer_sizes: []
  name: cnn
  num_classes: 32
  num_input_channels: 1
gnn_config:
  kernel_size: 25
  linear_layer_params:
    intermediate_layer_sizes: []
  monet_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  name: monet
  num_classes: 32
  num_node_features: 3
name: hybrid
num_classes: 4
