main:
  label: labels
  name: cifar
  transform_args: &id001
  - params: null
    type: ToPILImage
  - params: null
    type: ToTensor
  - params:
      mean:
      - 0.49139968
      - 0.48215827
      - 0.44653124
      std:
      - 0.24703233
      - 0.24348505
      - 0.26158768
    type: Normalize
  - params:
      size: [224,224]
    type: Resize
train:
  filepath:
    data: ./raw_data/CIFAR10/train
    indices_csv: null
  label: labels
  name: cifar
  split: train
  transform_args: *id001
train_val:
  train:
    filepath:
      data: ./raw_data/CIFAR10/train
      indices_csv: ./raw_data/CIFAR10/CIFAR10_train.csv
    label: labels
    name: cifar
    split: train
    transform_args: *id001
  val:
    filepath:
      data: ./raw_data/CIFAR10/train
      indices_csv: ./raw_data/CIFAR10/CIFAR10_validation.csv
    label: labels
    name: cifar
    split: val
    transform_args: *id001
val:
  filepath:
    data: ./raw_data/CIFAR10/test
    indices_csv: null
  label: labels
  name: cifar
  split: val
  transform_args: *id001
