main: &main
  name: mnist_slic
  add_slic_mask: true
  transform_args:
    - type: ToPILImage
      params: null
    - type: Grayscale
      params:
        num_output_channels: 1
    - type: ToTensor
      params: null # Need to write it at as null if no parameters are passed,
    - type: Normalize
      params:
        mean: [0.2860402]
        std: [0.3530239]
    - type: ToSLIC
      params:
        n_segments: 75
        add_seg: true
        add_img: true
    - type: RadiusGraph
      params:
        r: 5

train: &train
  <<: *main
  split: train
  filepath:
    image: /content/drive/MyDrive/SuperPixels/raw_data/FashionMNIST/train-images-idx3-ubyte
    labels: /content/drive/MyDrive/SuperPixels/raw_data/FashionMNIST/train-labels-idx1-ubyte
val: &val
  <<: *main
  split: val
  filepath: 
    image: /content/drive/MyDrive/SuperPixels/raw_data/FashionMNIST/t10k-images-idx3-ubyte
    labels: /content/drive/MyDrive/SuperPixels/raw_data/FashionMNIST/t10k-labels-idx1-ubyte
