main: &main
  label: labels
  name: cifar
  transform_args:
  - params: null
    type: ToPILImage
  - params: null
    type: ToTensor
  - params:
      mean:
      - 0.49139968
      - 0.48215827
      - 0.44653124
      std:
      - 0.24703233
      - 0.24348505
      - 0.26158768
    type: Normalize
train:
  << : *main
  filepath:
    data: ./raw_data/CIFAR10/train
    indices_csv: null
  split: train
train_val:
  train:
    << : *main
    filepath:
      data: ./raw_data/CIFAR10/train
      indices_csv: ./raw_data/CIFAR10/CIFAR10_train.csv
    split: train
  val:
    << : *main
    filepath:
      data: ./raw_data/CIFAR10/train
      indices_csv: ./raw_data/CIFAR10/CIFAR10_validation.csv
    split: val
val:
  << : *main
  filepath:
    data: ./raw_data/CIFAR10/test
    indices_csv: null
  split: val