name: projection

cnn_config:
  name: cnn
  num_input_channels: 1
  cnn_params:
    hidden_layer_sizes: [32,64,64]
  linear_layer_params:
    intermediate_layer_sizes: []
  num_classes: 32
  # input_dim: 28

gcn_config:
  name: multigat
  num_node_features: 3
  gat_params:
    hidden_layer_sizes: [32,64,64]
    num_heads: [2,2,2]
  linear_layer_params:
    intermediate_layer_sizes: []
  num_classes: 32

num_classes: 10