cnn_config:
  mlp_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  name: mlp
  num_classes: 32
  num_input_features: 1
gnn_config:
  gat_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  linear_layer_params:
    intermediate_layer_sizes: []
  name: gat
  num_classes: 32
  num_node_features: 3
name: projection
num_classes: 600
