main: &main
  name: cifar
  label: fine_labels
  transform_args:
    - type: ToPILImage
      params: null
    - type: Grayscale
      params:
        num_output_channels: 1
    - type: ToTensor
      params: null # Need to write it at as null if no parameters are passed,
    - type: Normalize
      params:
        mean: [0.5070746, 0.48654896,0.44091788]
        std: [0.26733422, 0.25643846, 0.27615058]

train_val:
  train: &train_2
    <<: *main
    split: train
    filepath:
      data: /content/drive/MyDrive/SuperPixels/raw_data/CIFAR100/train
      indices_csv: /content/drive/MyDrive/SuperPixels/raw_data/CIFAR100/CIFAR100_train.csv
  val: &val_2
    <<: *main
    split: val
    filepath: 
      data: /content/drive/MyDrive/SuperPixels/raw_data/CIFAR100/train
      indices_csv: /content/drive/MyDrive/SuperPixels/raw_data/CIFAR100/CIFAR100_validation.csv

train: &train
  <<: *main
  split: train
  filepath:
    data: /content/drive/MyDrive/SuperPixels/raw_data/CIFAR100/train
    indices_csv: null

val: &val
  <<: *main
  split: val
  filepath: 
    data: /content/drive/MyDrive/SuperPixels/raw_data/CIFAR100/test
    indices_csv: null

