cnn_config:
  batch_norm: false
  name: vgg
  num_classes: 32
  num_layers_freeze: 8
  pretrained: false
  vgg_version: '11'
gnn_config:
  kernel_size: 25
  linear_layer_params:
    intermediate_layer_sizes: []
  monet_params:
    hidden_layer_sizes:
    - 32
    - 64
    - 64
  name: monet
  num_classes: 32
  num_node_features: 5
name: projection
num_classes: 10
