main: &main
  label: fine_labels
  name: cifar
  transform_args:
  - params: null
    type: ToPILImage
  - params: null
    type: ToTensor
  - params:
      mean:
      - 0.5070746
      - 0.48654896
      - 0.44091788
      std:
      - 0.26733422
      - 0.25643846
      - 0.27615058
    type: Normalize
  - params:
      size:
      - 224
      - 224
    type: Resize
train:
  << : *main
  filepath:
    data: ./raw_data/CIFAR100/train
    indices_csv: null
  split: train
train_val:
  train:
    << : *main
    filepath:
      data: ./raw_data/CIFAR100/train
      indices_csv: ./raw_data/CIFAR100/CIFAR100_train.csv
    split: train
  val:
    << : *main
    filepath:
      data: ./raw_data/CIFAR100/train
      indices_csv: ./raw_data/CIFAR100/CIFAR100_validation.csv
    split: val
val:
  << : *main
  filepath:
    data: ./raw_data/CIFAR100/test
    indices_csv: null
  split: val